blog/app_blog/urls.py
from django.urls import path
from .import views

app_name='app_blog' 

urlpatterns = [    
    path('', views.index, name='index'),
    path('generales/', views.generales, name='generales'),
    path('programacion/', views.programacion, name='programacion'),
    path('videojuegos/', views.videojuegos, name='videojuegos'),
    path('tecnologia/', views.tecnologia, name='tecnologia'),
    path('tutoriales/', views.tutoriales, name='tutoriales'),
    path('<slug:slug>', views.post, name='post'),
    path('registro/',views.registro, name='registro'),
]

blog/blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings           
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app_blog.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

if settings.DEBUG:
    urlpatterns+=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/templates/base.html
{% load static %}


<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block titulo %}Blog Developer.pe{% endblock titulo %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'app_blog/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="{% static 'app_blog/vendor/fontawesome-free/css/all.min.css' %}" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

    <!-- Custom styles for this template -->
    <link href="{% static 'app_blog/css/clean-blog.css' %}" rel="stylesheet">

  </head>

  <body>

    <!-- Navigation -->
    <nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">
      <div class="container">
        <a class="navbar-brand" href="{% url 'app_blog:index' %}">Developer.pe</a>
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
          Menu
          <i class="fas fa-bars"></i>
        </button>
        <div class="collapse navbar-collapse" id="navbarResponsive">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item">
              <a class="nav-link" href="{% url 'app_blog:index' %}">Inicio</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'app_blog:generales' %}">Generales</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'app_blog:programacion' %}">Programación</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'app_blog:videojuegos' %}">Videojuegos</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'app_blog:tecnologia' %}">Tecnología</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'app_blog:tutoriales' %}">Tutoriales</a>
            </li>
          </ul>
        </div>

        {% block registro %}
        <div>
          {% if user.is_authenticated %}
            <a href="{% url 'logout' %}"" style="color:white">Cerrar Sesion</a> |
            <a class="user" href="{% url 'password_change' %}">Cambiar Password</a>
            <a href="#" style="color:white"> @{{user.username}}</a>
          {% else %}
            <a href="{% url 'login' %}" style="color:white"  >Inicial Sesión<a/>
            <a class="user" href="{% url 'app_blog:registro'  %}" style="color:white"  >Registro</a>  
          {% endif %}
        </div>
        {% endblock registro %}
        
      </div>
    </nav>




    <!-- Page Header -->
    <header class="masthead" style="background-image: 
    url({% block imagen %}

      {% static 'app_blog/img/home-bg.jpg' %}

    {% endblock %})">
|
      <div class="overlay"></div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <div class="site-heading">
              <h2>{% block titulo_principal %}Blog Developer.pe{% endblock titulo_principal %}</h2>
            </div>
          </div>
        </div>
      </div>
    </header>

  {% block barra_busqueda %}
    <div class="container">
      <div class="row">
        <div class="col-md-12 search">
          <form method="get">
              <div id="custom-search-input">
                <div class="input-group col-md-12">
                  <input type="text" class="form-control" placeholder="Buscar..." name="buscar" value = "{{ request.GET.buscar }}">
                  <span class="input-group-list">
                    <i class="icon icon-search"></i>
                    <button type="submit" class="boton btn-success">Buscar</button>
                  </span>
                </div>
              </div>
          </form>
        </div>
      </div>
    </div>
  {% endblock barra_busqueda %}

    <!-- Main Content -->
    <div class="container">
      <div class="row">
        <div class="col-lg-8 col-md-10 mx-auto">

    
          {% block contenido %}
          {% if posts %}
            {% for post in posts %}
                <div class="post-preview">
                  <a href="{% url 'app_blog:post' post.slug %}">
                    <h2 class="post-title">
                      {{ post.titulo }}
                    </h2>
                    <h3 class="post-subtitle">
                      {{ post.descripcion }}
                    </h3>
                  </a>
                  <p class="post-meta">Escrito por
                    <strong>{{ post.autor }}</strong>   el
                    {{ post.fecha_creacion }}</p>
                </div>
                <hr>
            {% endfor %}
          {% else %}
            <h1>No existen post registrados!</h1>
          {% endif %}
                


          {% endblock contenido %}

        </div>
      </div>
    </div>

   <div class="row">
     <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
       <div class="col-md-6 col-sm-6 col-lg-6 col-xs-6 float-left">
         {% if posts.has_previous %}
              <div class="clearfix">
                <a href="?page={{ posts.previous_page_number }}{% if request.GET.search %}&q={{ request.GET.search }}{% endif %}" class="btn btn-primary float-left">Anterior</a>
              </div>
         {% endif %}
       </div>
     </div>
     <div class="col-md-12 col-lg-12 col-sm-12 col-xs-12">
       <div class="col-md-6 col-sm-6 col-lg-6 col-xs-6  float-right">
         {% if posts.has_next %}
              <div class="clearfix">
                <a href="?page={{ posts.next_page_number }}{% if request.GET.search %}&q={{ request.GET.search }}{% endif %}" class="btn btn-primary float-right">Siguiente</a>
              </div>
         {% endif %}
       </div>
     </div>
   </div>



    <hr>

    <!-- Footer -->
    <footer>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 col-md-10 mx-auto">
            <ul class="list-inline text-center">
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fas fa-circle fa-stack-2x"></i>
                    <i class="fab fa-twitter fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fas fa-circle fa-stack-2x"></i>
                    <i class="fab fa-facebook-f fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
              <li class="list-inline-item">
                <a href="#">
                  <span class="fa-stack fa-lg">
                    <i class="fas fa-circle fa-stack-2x"></i>
                    <i class="fab fa-github fa-stack-1x fa-inverse"></i>
                  </span>
                </a>
              </li>
            </ul>
            <p class="copyright text-muted">Copyright &copy; Your Website 2018</p>
          </div>
        </div>
      </div>
    </footer>

    <!-- Bootstrap core JavaScript -->
    <script src="{% static 'app_blog/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'app_blog/vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

    <!-- Custom scripts for this template -->
    <script src="{% static 'app_blog/js/clean-blog.min.js' %}"></script>

  </body>

</html>